services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - cloudflare_wordpress

  #Defining wordpress service
  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - cloudflare_wordpress

  #Cloudflare tunnel / zero trust
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
     - cloudflare_wordpress

volumes:
  mysqldb_data:
  wordpress_data:

networks:
  cloudflare_wordpress:
    drive: bridge
